"""Generate a compilable COMSOL Java model source file (no COMSOL required).

This is the building block for the *COMSOL-less* workflow: an agent can author a
Java model on a machine without COMSOL, then move the file to a COMSOL machine and
run ``comsolcompile <file>.java`` + ``comsolbatch -java <ClassName>`` to produce a
``.mph``. Everything here is plain string templating — it never imports or touches
the COMSOL API, so it runs anywhere Python runs.
"""

from __future__ import annotations

import os
import re
from typing import Any, Dict, List, Optional


def _java_id(name: str) -> str:
    """Sanitize an arbitrary string into a valid Java identifier."""
    cleaned = re.sub(r"[^A-Za-z0-9_]", "_", name or "Model")
    if not cleaned:
        cleaned = "Model"
    if cleaned[0].isdigit():
        cleaned = "_" + cleaned
    return cleaned


def _jstr(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return '"' + escaped + '"'


def _j_double_array(values: List[float]) -> str:
    return "new String[]{" + ", ".join(_jstr(str(float(v))) for v in values) + "}"


def _geom_feature(g: Dict[str, Any], geom_tag: str) -> str:
    tag = _java_id(g.get("tag") or g.get("type") or "feat")
    kind = (g.get("type") or "block").lower()
    jg = _jstr(geom_tag)
    if kind == "block":
        lines = [
            f'        model.geom({jg}).feature().create({_jstr(tag)}, "Block");',
            f'        model.geom({jg}).feature({_jstr(tag)}).set("size", {_j_double_array(g.get("size", [0.1, 0.1, 0.1]))});',
        ]
        if g.get("pos"):
            lines.append(f'        model.geom({jg}).feature({_jstr(tag)}).set("pos", {_j_double_array(g["pos"])});')
        return "\n".join(lines)
    if kind == "cylinder":
        lines = [
            f'        model.geom({jg}).feature().create({_jstr(tag)}, "Cylinder");',
            f'        model.geom({jg}).feature({_jstr(tag)}).set("r", {_jstr(str(float(g.get("r", 0.05))))});',
            f'        model.geom({jg}).feature({_jstr(tag)}).set("h", {_jstr(str(float(g.get("h", 0.2))))});',
        ]
        if g.get("pos"):
            lines.append(f'        model.geom({jg}).feature({_jstr(tag)}).set("pos", {_j_double_array(g["pos"])});')
        if g.get("axis"):
            lines.append(f'        model.geom({jg}).feature({_jstr(tag)}).set("axis", {_jstr(g["axis"])});')
        return "\n".join(lines)
    if kind == "sphere":
        lines = [
            f'        model.geom({jg}).feature().create({_jstr(tag)}, "Sphere");',
            f'        model.geom({jg}).feature({_jstr(tag)}).set("r", {_jstr(str(float(g.get("r", 0.1))))});',
        ]
        if g.get("pos"):
            lines.append(f'        model.geom({jg}).feature({_jstr(tag)}).set("pos", {_j_double_array(g["pos"])});')
        return "\n".join(lines)
    return f'        // TODO: add geometry feature of type {kind!r} for tag {tag!r}'


def generate_model_java_source(
    class_name: str = "GeneratedModel",
    model_version: str = "6.2",
    spec: Optional[Dict[str, Any]] = None,
) -> str:
    """Return Java source for a standalone, compilable COMSOL model program.

    ``spec`` is an optional dict with keys ``geometries``, ``physics``,
    ``materials``, ``studies``, ``save``, ``geom_tag``, ``mesh_tag``, ``dims``.
    If omitted, a documented heat-transfer example skeleton is emitted instead.
    """
    spec = spec or {}
    cls = _java_id(class_name)

    out: List[str] = []
    out.append("// Generated by comsol-mcp (generate_model_java).")
    out.append("// This file is STANDALONE and requires COMSOL to compile and run:")
    out.append("//   comsolcompile " + cls + ".java")
    out.append("//   comsolbatch -java " + cls)
    out.append("// Edit the marked sections freely; exact API may vary by COMSOL version.")
    out.append("import com.comsol.model.*;")
    out.append("import com.comsol.model.util.*;")
    out.append("")
    out.append("public class " + cls + " {")
    out.append("    public static void main(String[] args) {")
    out.append("        // ModelUtil.initStandalone(true);  // uncomment only for a non-batch standalone run")
    out.append('        Model model = ModelUtil.create("' + cls + '");')
    out.append('        model.modelNode().version("' + str(model_version) + '");')
    out.append("")

    # Geometry
    out.append("        // ===== Geometry =====")
    geom_tag = _java_id(spec.get("geom_tag") or "geom1")
    dims = int(spec.get("dims") or 3)
    jg = _jstr(geom_tag)
    out.append(f'        model.geom().create({jg}, {dims});')
    geometries = spec.get("geometries") or []
    if geometries:
        for g in geometries:
            out.append(_geom_feature(g, geom_tag))
    else:
        out.append(f'        model.geom({jg}).feature().create("blk1", "Block");')
        out.append(f'        model.geom({jg}).feature("blk1").set("size", new String[]{{"0.1","0.1","0.1"}});')
    out.append(f'        model.geom({jg}).run();')
    out.append("")

    # Physics
    out.append("        // ===== Physics =====")
    physics = spec.get("physics") or []
    if physics:
        for p in physics:
            tag = _java_id(p.get("tag") or p.get("interface") or "phys")
            interface = p.get("interface") or "HeatTransferInSolids"
            out.append(f'        model.physics().create({_jstr(tag)}, {_jstr(interface)}, {jg});')
            out.append(f'        model.physics({_jstr(tag)}).feature().create({_jstr(tag + "1")}, {_jstr(interface)});')
    else:
        out.append(f'        model.physics().create("ht", "HeatTransferInSolids", {jg});')
        out.append('        model.physics("ht").feature().create("ht1", "HeatTransferInSolids");')
    out.append("")

    # Materials
    out.append("        // ===== Materials =====")
    materials = spec.get("materials") or []
    if materials:
        for m in materials:
            tag = _java_id(m.get("tag") or "mat")
            out.append(f'        model.material().create({_jstr(tag)});')
            out.append(f'        // TODO: set material properties on model.material({_jstr(tag)})')
    else:
        out.append("        // (no materials specified)")
    out.append("")

    # Mesh
    out.append("        // ===== Mesh =====")
    mesh_tag = _java_id(spec.get("mesh_tag") or "mesh1")
    out.append(f'        model.mesh().create({_jstr(mesh_tag)}, {jg});')
    out.append(f'        model.mesh({_jstr(mesh_tag)}).run();')
    out.append("")

    # Study / Solver
    out.append("        // ===== Study / Solver =====")
    studies = spec.get("studies") or [{"tag": "std1", "type": "Stationary"}]
    for s in studies:
        tag = _java_id(s.get("tag") or "std1")
        stype = s.get("type") or "Stationary"
        out.append(f'        model.study().create({_jstr(tag)}, {_jstr(stype)});')
        out.append(f'        model.solver().create({_jstr("sol_" + tag)}, {_jstr(stype)}, {_jstr(tag)});')
        out.append(f'        model.solver({_jstr("sol_" + tag)}).runAll();')
    out.append("")

    # Save
    out.append("        // ===== Save =====")
    save = spec.get("save") or (cls + ".mph")
    out.append(f'        model.save({_jstr(save)});')
    out.append("    }")
    out.append("}")
    return "\n".join(out) + "\n"


def write_model_java(
    filepath: str,
    class_name: str = "GeneratedModel",
    model_version: str = "6.2",
    spec: Optional[Dict[str, Any]] = None,
) -> Dict[str, Any]:
    """Render the Java source and write it to ``filepath``. Returns a result dict."""
    source = generate_model_java_source(class_name, model_version, spec)
    parent = os.path.dirname(filepath)
    if parent:
        os.makedirs(parent, exist_ok=True)
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(source)
    return {
        "ok": True,
        "dry_run": True,
        "needs_comsol_to_compile": True,
        "path": filepath,
        "lines": source.count("\n") + 1,
    }
